import { useSession } from 'next-auth/client';
import { Provider } from 'next-auth/client'
import '../styles/globals.css'
import Head from 'next/head';
import Navbar from '../components/Navbar';
import LeftPanel from '../components/LeftPanel';

function MyApp({ Component, pageProps }) {
  const [ session, loading ] = useSession()

  return (
    <Provider session={pageProps.session}>
      <Head>
        <title>Financial Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {!session?.user && <LeftPanel />}
      <Component {...pageProps} />
    </Provider>
  )
}

export default MyApp
